server {
    listen 80;
    server_name localhost;

    root /var/www/html/public;
    index index.php;

    charset utf-8;
    client_max_body_size 20M;

    # Segurança
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
    add_header Referrer-Policy "strict-origin-when-cross-origin";
    add_header X-Robots-Tag "noindex, nofollow";

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass nome_do_projeto_laravel_app:9000;
        fastcgi_index index.php;
        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;

        fastcgi_read_timeout 300;
        fastcgi_hide_header X-Powered-By;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}


############################################################################################
# E no Laravel configure CORS

# Arquivo:

# config/cors.php
# Exemplo profissional
# return [

#     'paths' => ['api/*', 'sanctum/csrf-cookie'],

#     'allowed_methods' => ['*'],

#     'allowed_origins' => [
#         'http://localhost:3000',
#         'https://app.seusite.com',
#     ],

#     'allowed_origins_patterns' => [],

#     'allowed_headers' => ['*'],

#     'exposed_headers' => [],

#     'max_age' => 0,

#     'supports_credentials' => true,

# ];